version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_educa_flow
    restart: always
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: postgres_educa_flow
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: